extends: default

rules:
  line-length: disable
  truthy: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  trailing-spaces: enable
  new-line-at-end-of-file: enable
ignore: |
  helm/**/templates/**
