extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  trailing-spaces: enable
  new-line-at-end-of-file: enable
