{{- if and .Values.bakery.enabled (not .Values.poundcake.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: stackstorm-startup-markers
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
type: Opaque
stringData:
  bakery_db_ready: "false"
{{- end }}
