{{- if .Values.bakery.enabled }}
{{- $bakery := .Values.bakery | default dict }}
{{- $bakeryServiceAccount := $bakery.serviceAccount | default dict }}
{{- $create := .Values.serviceAccount.create }}
{{- if hasKey $bakeryServiceAccount "create" }}
{{- $create = $bakeryServiceAccount.create }}
{{- end }}
{{- if $create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "poundcake.bakeryServiceAccountName" . }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
  {{- with $bakeryServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
