apiVersion: v1
kind: ConfigMap
metadata:
  name: stackstorm-config
  labels:
    {{- include "poundcake-standalone.labels" . | nindent 4 }}
data:
  st2.conf.template: |
{{ .Files.Get "files/st2-config/st2.conf.template" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackstorm-scripts
  labels:
    {{- include "poundcake-standalone.labels" . | nindent 4 }}
data:
  st2-entrypoint.sh: |
{{ .Files.Get "files/st2-init/st2-entrypoint.sh" | indent 4 }}
  stackstorm-pack-sync.sh: |
{{ .Files.Get "files/st2-init/stackstorm-pack-sync.sh" | indent 4 }}
  automated-setup.sh: |
{{ .Files.Get "files/scripts/automated-setup.sh" | indent 4 }}
  mongodb-init.sh: |
{{ .Files.Get "files/mongodb-init/01-create-st2-user.sh" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poundcake-scripts
  labels:
    {{- include "poundcake-standalone.labels" . | nindent 4 }}
data:
  mariadb-init.sh: |
{{ .Files.Get "files/mariadb-init/01-create-databases.sh" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poundcake-alembic
  labels:
    {{- include "poundcake-standalone.labels" . | nindent 4 }}
data:
  alembic.ini: |
{{ .Files.Get "files/poundcake-alembic/alembic.ini" | indent 4 }}
  env.py: |
{{ .Files.Get "files/poundcake-alembic/env.py" | indent 4 }}
  script.py.mako: |
{{ .Files.Get "files/poundcake-alembic/script.py.mako" | indent 4 }}
  versions__init__.py: |
{{ .Files.Get "files/poundcake-alembic/versions__init__.py" | indent 4 }}
  2026_02_03_1600_initial_schema.py: |
{{ .Files.Get "files/poundcake-alembic/2026_02_03_1600_initial_schema.py" | indent 4 }}
