{{- if ne (default "full" .Values.deployment.mode) "bakery-only" }}

{{- if .Values.mariadbOperator.enabled }}
{{/*
Generate secrets for MariaDB root and user passwords if not using existing secrets
*/}}

{{- if not .Values.mariadbOperator.server.rootPasswordSecret }}
{{- $secret := lookup "v1" "Secret" (include "poundcake.mariadbNamespace" .) (include "poundcake.mariadbRootSecretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poundcake.mariadbRootSecretName" . }}
  namespace: {{ include "poundcake.mariadbNamespace" . }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if .Values.mariadbOperator.server.rootPassword }}
  password: {{ .Values.mariadbOperator.server.rootPassword | b64enc | quote }}
  {{- else if $secret }}
  password: {{ index $secret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if not .Values.mariadbOperator.user.passwordSecret }}
---
{{- $userSecret := lookup "v1" "Secret" (include "poundcake.mariadbNamespace" .) (include "poundcake.mariadbUserSecretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poundcake.mariadbUserSecretName" . }}
  namespace: {{ include "poundcake.mariadbNamespace" . }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if .Values.mariadbOperator.user.password }}
  password: {{ .Values.mariadbOperator.user.password | b64enc | quote }}
  {{- else if $userSecret }}
  password: {{ index $userSecret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
