{{- if ne (default "full" .Values.deployment.mode) "bakery-only" }}

{{- if .Values.mariadbOperator.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "poundcake.fullname" . }}-db
  namespace: {{ include "poundcake.mariadbNamespace" . }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  mariaDbRef:
    name: {{ include "poundcake.mariadbName" . }}
    waitForIt: true

  name: {{ include "poundcake.mariadbDatabaseName" . }}

  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci

  retryInterval: 5s
{{- end }}
{{- end }}
