{{- if .Values.poundcake.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: poundcake-scripts
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
data:
  mariadb-init.sh: |
{{ .Files.Get "files/mariadb-init/01-create-databases.sh" | indent 4 }}
  legacy-schema-migrate.sh: |
{{ .Files.Get "files/mariadb-init/20-legacy-schema-migrate.sh" | indent 4 }}
{{- end }}
