{{- if .Values.poundcake.enabled }}
{{- if eq (include "poundcake.databaseMode" .) "embedded" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poundcake-mariadb
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.mariadb.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.mariadb.size }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.mariadb.storageClassName) | nindent 2 }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-mongo
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.mongo.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.mongo.size }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.mongo.storageClassName) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-rabbitmq
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.rabbitmq.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.rabbitmq.size }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.rabbitmq.storageClassName) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-redis
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.redis.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.redis.size }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.redis.storageClassName) | nindent 2 }}
{{- if and (eq (include "poundcake.stackstormThirdPartyPacksEnabled" .) "true") (eq (include "poundcake.stackstormSharedStorageEnabled" .) "true") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-pack-kubernetes
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.stackstormSharedStorage.accessMode | default "ReadWriteMany" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.stackstormSharedStorage.packVolumeSize }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" (include "poundcake.stackstormSharedStorageClassName" .)) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-pack-openstack
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.stackstormSharedStorage.accessMode | default "ReadWriteMany" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.stackstormSharedStorage.packVolumeSize }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" (include "poundcake.stackstormSharedStorageClassName" .)) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-virtualenv-kubernetes
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.stackstormSharedStorage.accessMode | default "ReadWriteMany" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.stackstormSharedStorage.virtualenvVolumeSize }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" (include "poundcake.stackstormSharedStorageClassName" .)) | nindent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackstorm-virtualenv-openstack
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.stackstormSharedStorage.accessMode | default "ReadWriteMany" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.stackstormSharedStorage.virtualenvVolumeSize }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" (include "poundcake.stackstormSharedStorageClassName" .)) | nindent 2 }}
{{- end }}
{{- end }}
