{{- if and .Values.auth.enabled .Values.auth.activeDirectory.enabled (not .Values.auth.activeDirectory.serverUri) -}}
{{- fail "auth.activeDirectory.serverUri is required when auth.activeDirectory.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.activeDirectory.enabled (not .Values.auth.activeDirectory.userBaseDn) -}}
{{- fail "auth.activeDirectory.userBaseDn is required when auth.activeDirectory.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.auth0.enabled (not .Values.auth.auth0.shared.domain) -}}
{{- fail "auth.auth0.shared.domain is required when auth.auth0.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.auth0.enabled (not (or .Values.auth.auth0.ui.enabled .Values.auth.auth0.cli.enabled)) -}}
{{- fail "auth.auth0.ui.enabled or auth.auth0.cli.enabled must be true when auth.auth0.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.auth0.enabled .Values.auth.auth0.ui.enabled (not .Values.auth.auth0.ui.clientId) -}}
{{- fail "auth.auth0.ui.clientId is required when auth.auth0.ui.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.auth0.enabled .Values.auth.auth0.cli.enabled (not .Values.auth.auth0.cli.clientId) -}}
{{- fail "auth.auth0.cli.clientId is required when auth.auth0.cli.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.azureAd.enabled (not .Values.auth.azureAd.shared.tenant) -}}
{{- fail "auth.azureAd.shared.tenant is required when auth.azureAd.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.azureAd.enabled (not (or .Values.auth.azureAd.ui.enabled .Values.auth.azureAd.cli.enabled)) -}}
{{- fail "auth.azureAd.ui.enabled or auth.azureAd.cli.enabled must be true when auth.azureAd.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.azureAd.enabled .Values.auth.azureAd.ui.enabled (not .Values.auth.azureAd.ui.clientId) -}}
{{- fail "auth.azureAd.ui.clientId is required when auth.azureAd.ui.enabled=true." -}}
{{- end -}}

{{- if and .Values.auth.enabled .Values.auth.azureAd.enabled .Values.auth.azureAd.cli.enabled (not .Values.auth.azureAd.cli.clientId) -}}
{{- fail "auth.azureAd.cli.clientId is required when auth.azureAd.cli.enabled=true." -}}
{{- end -}}
