{{- if .Values.poundcake.enabled }}
{{- if eq (include "poundcake.databaseMode" .) "embedded" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poundcake-mariadb
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.mariadb.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.mariadb.size }}
   {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.mariadb.storageClassName) | nindent 2 }}
---
{{- if .Values.persistence.legacyBackup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poundcake.name" . }}-legacy-backup
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.persistence.legacyBackup.accessMode | default "ReadWriteOnce" }}"]
  resources:
    requests:
      storage: {{ .Values.persistence.legacyBackup.size }}
  {{- include "poundcake.pvcStorageClass" (dict "root" . "pvcStorageClass" .Values.persistence.legacyBackup.storageClassName) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
