{{- if ne (default "full" .Values.deployment.mode) "bakery-only" }}

{{- if and .Values.rabbitmq.enabled (not .Values.rabbitmq.external) }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "poundcake.stackstormRabbitmqName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
    stackstorm.io/log-group: stackstorm
    stackstorm.io/log-role: infra
spec:
  replicas: {{ .Values.rabbitmq.replicas | default 1 }}

  {{- if .Values.rabbitmq.image }}
  image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
  {{- end }}

  resources:
    {{- if .Values.rabbitmq.resources }}
    {{- toYaml .Values.rabbitmq.resources | nindent 4 }}
    {{- else }}
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
    {{- end }}

  rabbitmq:
    additionalConfig: |
      default_user = {{ .Values.rabbitmq.auth.username | default "stackstorm" }}
      default_pass = {{ .Values.rabbitmq.auth.password | default "stackstorm" }}
      default_vhost = {{ .Values.rabbitmq.vhost | default "/" }}

  persistence:
    {{- if .Values.rabbitmq.persistence }}
    storageClassName: {{ .Values.rabbitmq.persistence.storageClassName | default "" }}
    storage: {{ .Values.rabbitmq.persistence.size | default "8Gi" }}
    {{- else }}
    storage: 8Gi
    {{- end }}

  service:
    type: {{ .Values.rabbitmq.service.type | default "ClusterIP" }}

  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              stackstorm.io/log-group: stackstorm
              stackstorm.io/log-role: infra
{{- end }}
{{- end }}
