{{- if .Values.bakery.enabled }}
{{- if not .Values.bakery.servicenow.existingSecret }}
{{- if or .Values.bakery.servicenow.password .Values.bakery.jira.apiToken .Values.bakery.github.token .Values.bakery.pagerduty.apiKey .Values.bakery.rackspaceCore.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poundcake.fullname" . }}-bakery
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: bakery
type: Opaque
data:
  {{- if .Values.bakery.servicenow.password }}
  servicenow-password: {{ .Values.bakery.servicenow.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.bakery.jira.apiToken }}
  jira-api-token: {{ .Values.bakery.jira.apiToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.bakery.github.token }}
  github-token: {{ .Values.bakery.github.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.bakery.pagerduty.apiKey }}
  pagerduty-api-key: {{ .Values.bakery.pagerduty.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.bakery.rackspaceCore.password }}
  rackspace-core-password: {{ .Values.bakery.rackspaceCore.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
