{{- if and (or .Values.bakery.enabled (eq (default "full" .Values.deployment.mode) "bakery-only")) .Values.bakery.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "poundcake.bakeryName" . }}-httproute
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: bakery-gateway
  {{- with .Values.bakery.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- range .Values.bakery.gateway.hostnames }}
  - {{ . | quote }}
  {{- end }}
  parentRefs:
  - name: {{ .Values.bakery.gateway.gatewayName }}
    {{- if .Values.bakery.gateway.gatewayNamespace }}
    namespace: {{ .Values.bakery.gateway.gatewayNamespace }}
    {{- end }}
    {{- if .Values.bakery.gateway.listener.name }}
    sectionName: {{ .Values.bakery.gateway.listener.name }}
    {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "poundcake.bakeryName" . }}
      port: {{ .Values.bakery.service.port }}
{{- end }}
