
{{- if .Values.mariadbOperator.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "poundcake.fullname" . }}-user
  namespace: {{ include "poundcake.mariadbNamespace" . }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  mariaDbRef:
    name: {{ include "poundcake.mariadbName" . }}
    waitForIt: true

  name: {{ include "poundcake.mariadbUsername" . }}

  passwordSecretKeyRef:
    name: {{ include "poundcake.mariadbUserSecretName" . }}
    key: {{ .Values.mariadbOperator.user.passwordSecretKey | default "password" }}

  maxUserConnections: {{ .Values.mariadbOperator.user.maxUserConnections | default 20 }}

  host: "%"

  retryInterval: 5s
{{- end }}
