
{{- if .Values.mariadbOperator.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ include "poundcake.fullname" . }}-grant
  namespace: {{ include "poundcake.mariadbNamespace" . }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  mariaDbRef:
    name: {{ include "poundcake.mariadbName" . }}
    waitForIt: true

  privileges:
    {{- range .Values.mariadbOperator.grants.privileges }}
    - {{ . | quote }}
    {{- end }}

  database: {{ include "poundcake.mariadbDatabaseName" . }}

  table: "*"

  username: {{ include "poundcake.mariadbUsername" . }}

  grantOption: false

  host: "%"

  retryInterval: 5s
{{- end }}
