
{{- if and .Values.mongodb.enabled (not .Values.mongodb.external) }}
{{- $secretName := printf "%s-secret" (include "poundcake.stackstormMongoName" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $rootPassword := "" }}
{{- $username := "" }}
{{- $password := "" }}
{{- if $existingSecret }}
  {{- $rootPassword = index $existingSecret.data "mongodb-root-password" | b64dec }}
  {{- $username = index $existingSecret.data "mongodb-username" | b64dec }}
  {{- $password = index $existingSecret.data "mongodb-password" | b64dec }}
{{- else }}
  {{- $rootPassword = .Values.mongodb.auth.rootPassword | default "stackstorm" }}
  {{- $username = .Values.mongodb.auth.username | default "stackstorm" }}
  {{- $password = .Values.mongodb.auth.password | default "stackstorm" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  mongodb-root-password: {{ $rootPassword | b64enc | quote }}
  mongodb-username: {{ $username | b64enc | quote }}
  mongodb-password: {{ $password | b64enc | quote }}
{{- end }}
