# ____                        _  ____      _
# |  _ \ ___  _   _ _ __   __| |/ ___|__ _| | _____
# | |_) / _ \| | | | '_ \ / _` | |   / _` | |/ / _ \
# |  __/ (_) | |_| | | | | (_| | |__| (_| |   <  __/
# |_|   \___/ \__,_|_| |_|\__,_|\____\__,_|_|\_\___|
#
# ╔════════════════════════════════════════════════════════════════╗
# ____                        _  ____      _         
# |  _ \ ___  _   _ _ __   __| |/ ___|__ _| | _____ 
# | |_) / _ \| | | | '_ \ / _` | |   / _` | |/ / _ \
# |  __/ (_) | |_| | | | | (_| | |__| (_| |   <  __/
# |_|   \___/ \__,_|_| |_|\__,_|\____\__,_|_|\_\___|
# ╚════════════════════════════════════════════════════════════════╝

{{- if and .Values.stackstorm.mongodb.enabled (not .Values.stackstorm.mongodb.external) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "poundcake.fullname" . }}-mongodb
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.stackstorm.mongodb.service.type }}
  ports:
  - port: {{ .Values.stackstorm.mongodb.service.port }}
    targetPort: mongodb
    protocol: TCP
    name: mongodb
  selector:
    {{- include "poundcake.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
