{{- if and .Values.stackstorm.mongodb.enabled (not .Values.stackstorm.mongodb.external) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "poundcake.fullname" . }}-mongodb
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.stackstorm.mongodb.service.type }}
  ports:
  - port: {{ .Values.stackstorm.mongodb.service.port }}
    targetPort: mongodb
    protocol: TCP
    name: mongodb
  selector:
    {{- include "poundcake.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
