
{{- if and .Values.mongodb.enabled (not .Values.mongodb.external) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poundcake.fullname" . }}-mongodb-secret
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | default "stackstorm" | b64enc | quote }}
  mongodb-username: {{ .Values.mongodb.auth.username | default "stackstorm" | b64enc | quote }}
  mongodb-password: {{ .Values.mongodb.auth.password | default "stackstorm" | b64enc | quote }}
{{- end }}
