
{{- if and (not .Values.stackstorm.existingSecret) (or .Values.stackstorm.apiKey .Values.stackstorm.authToken) }}
{{- $secretName := printf "%s-stackstorm" (include "poundcake.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if .Values.stackstorm.apiKey }}
  {{- $apiKeyValue := .Values.stackstorm.apiKey }}
  {{- if $existingSecret }}
    {{- $existingApiKey := index $existingSecret.data .Values.stackstorm.secretKeys.apiKey }}
    {{- if $existingApiKey }}
      {{- $apiKeyValue = $existingApiKey | b64dec }}
    {{- end }}
  {{- end }}
  {{ .Values.stackstorm.secretKeys.apiKey }}: {{ $apiKeyValue | b64enc | quote }}
  {{- end }}
  {{- if .Values.stackstorm.authToken }}
  {{- $authTokenValue := .Values.stackstorm.authToken }}
  {{- if $existingSecret }}
    {{- $existingAuthToken := index $existingSecret.data .Values.stackstorm.secretKeys.authToken }}
    {{- if $existingAuthToken }}
      {{- $authTokenValue = $existingAuthToken | b64dec }}
    {{- end }}
  {{- end }}
  {{ .Values.stackstorm.secretKeys.authToken }}: {{ $authTokenValue | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if .Values.auth.enabled }}
---
{{- $secretName := printf "%s-admin" (include "poundcake.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $adminPassword := "" }}
{{- if $existingSecret }}
  {{- $adminPassword = index $existingSecret.data "password" | b64dec }}
{{- else }}
  {{- $adminPassword = randAlphaNum 24 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "poundcake.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ $adminPassword | b64enc | quote }}
{{- end }}
