apiVersion: v2
name: poundcake
description: All-in-one auto-remediation platform with integrated StackStorm, bridging Prometheus Alertmanager with automated remediation actions
type: application
version: 2.0.13
appVersion: "1.0.3"
maintainers:
  - name: Jake Briggs
keywords:
  - alertmanager
  - stackstorm
  - auto-remediation
  - prometheus
  - automation
  - all-in-one
home: https://github.com/aedan/poundCake
sources:
  - https://github.com/aedan/poundCake
dependencies:
  - name: rabbitmq
    version: "14.6.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
    tags:
      - stackstorm-deps
  - name: redis
    version: "19.6.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    tags:
      - stackstorm-deps
  - name: stackstorm-ha
    version: "1.1.0"
    repository: "https://helm.stackstorm.com/"
    condition: stackstorm.chart.enabled
    alias: stackstorm-chart
    tags:
      - stackstorm
