apiVersion: v2
name: poundcake
description: All-in-one auto-remediation platform with integrated StackStorm, bridging Prometheus Alertmanager with automated remediation actions
type: application
version: 2.0.22
appVersion: "main"
maintainers:
  - name: Jake Briggs
keywords:
  - alertmanager
  - stackstorm
  - auto-remediation
  - prometheus
  - automation
  - all-in-one
home: https://github.com/aedan/poundCake
sources:
  - https://github.com/aedan/poundCake
dependencies:
  - name: stackstorm-ha
    version: "1.1.0"
    repository: "https://helm.stackstorm.com/"
    condition: stackstorm.chart.enabled
    alias: stackstorm-chart
    tags:
      - stackstorm
