apiVersion: v2
name: poundcake
description: Auto-remediation framework bridging Prometheus Alertmanager with StackStorm
type: application
version: 1.1.0
appVersion: "1.0.2"
maintainers:
  - name: Jake Briggs
keywords:
  - alertmanager
  - stackstorm
  - auto-remediation
  - prometheus
  - automation
home: https://github.com/aedan/poundCake
sources:
  - https://github.com/aedan/poundCake
