#!/usr/bin/env python3
#  ____                        _  ____      _
# |  _ \ ___  _   _ _ __   __| |/ ___|__ _| | _____
# | |_) / _ \| | | | '_ \ / _` | |   / _` | |/ / _ \
# |  __/ (_) | |_| | | | | (_| | |__| (_| |   <  __/
# |_|   \___/ \__,_|_| |_|\__,_|\____\__,_|_|\_\___|
#
"""Timer Service - Monitors oven executions and updates completion status."""

#!/usr/bin/env python3
import os
import time
import requests
from datetime import datetime, timezone

POUNDCAKE_API_URL = os.getenv("POUNDCAKE_API_URL", "http://api:8000/api/v1").rstrip("/")
ST2_API_URL = os.getenv("ST2_API_URL", "http://stackstorm-api:9101/v1").rstrip("/")
TIMER_INTERVAL = int(os.getenv("TIMER_INTERVAL", "10"))

# Read ST2_API_KEY from file (generated by st2client)
ST2_API_KEY_FILE = "/app/config/st2_api_key"


def get_st2_api_key():
    """Read ST2 API key from file."""
    try:
        if os.path.exists(ST2_API_KEY_FILE):
            with open(ST2_API_KEY_FILE, "r") as f:
                key = f.read().strip()
                if key:
                    return key
    except Exception as e:
        log(f"Error reading ST2 API key: {e}")
    return None


# System request ID for polling operations (distinguishes system calls from alert processing)
SYSTEM_REQ_ID = "SYSTEM-TIMER-POLL"


def log(message: str, req_id: str = "SYSTEM"):
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] [req_id: {req_id}] timer: {message}", flush=True)


def extract_error_message(st2_data: dict, st2_result: dict) -> str:
    """Extract error message from StackStorm execution data."""
    error_parts = []

    # Check for error in result
    if st2_result:
        # Shell command errors (core.local, core.remote)
        if isinstance(st2_result, dict):
            stderr = st2_result.get("stderr", "")
            if stderr:
                error_parts.append(f"stderr: {stderr[:500]}")  # Limit length

            exit_code = st2_result.get("exit_code") or st2_result.get("return_code")
            if exit_code and exit_code != 0:
                error_parts.append(f"exit_code: {exit_code}")

            # For remote executions with multiple hosts
            for key, value in st2_result.items():
                if isinstance(value, dict) and value.get("failed"):
                    error_parts.append(f"{key}: {value.get('stderr', 'execution failed')}")

    # Check for error message in execution data
    if "error" in st2_data:
        error_parts.append(f"error: {st2_data['error']}")

    # Get failure reason if available
    if "result" in st2_data and isinstance(st2_data["result"], dict):
        failure_reason = st2_data["result"].get("error") or st2_data["result"].get("message")
        if failure_reason:
            error_parts.append(f"reason: {failure_reason}")

    return " | ".join(error_parts) if error_parts else "Execution failed"


def monitor_ovens():
    headers = {"Content-Type": "application/json"}
    st2_api_key = get_st2_api_key()
    if st2_api_key:
        headers["St2-Api-Key"] = st2_api_key
    else:
        log("WARNING: No ST2 API key found - StackStorm requests may fail")

    try:
        # 1. Get ovens currently in flight (system operation, not tied to specific alert)
        resp = requests.get(
            f"{POUNDCAKE_API_URL}/ovens",
            params={"processing_status": "processing"},
            headers={"X-Request-ID": SYSTEM_REQ_ID},
            timeout=10,
        )
        ovens = resp.json()

        for oven in ovens:
            # Switch from system polling req_id to alert's req_id for all subsequent operations
            # This ensures end-to-end traceability for this specific alert
            req_id = oven.get("req_id", "UNKNOWN")
            action_id = oven.get("action_id")

            # Add trace ID to all monitoring calls
            headers["X-Request-ID"] = req_id

            # 2. Check ST2 Status
            st2_resp = requests.get(
                f"{ST2_API_URL}/executions/{action_id}", headers=headers, timeout=10
            )
            if st2_resp.status_code == 200:
                st2_data = st2_resp.json()

                # Ensure response is a dict, not a string
                if not isinstance(st2_data, dict):
                    log(
                        f"Unexpected ST2 response type for action {action_id}: {type(st2_data)}",
                        req_id=req_id,
                    )
                    continue

                st2_status = st2_data.get("status")
                st2_result = st2_data.get("result")  # Extract the action output

                # 3. If finished, update API
                if st2_status in ["succeeded", "failed", "canceled"]:
                    new_status = "complete"
                    current_time = datetime.now(timezone.utc).isoformat()

                    # Prepare update payload
                    update_data = {
                        "processing_status": new_status,
                        "st2_status": st2_status,
                        "completed_at": current_time,
                    }

                    # Include action result if available
                    if st2_result is not None:
                        update_data["action_result"] = st2_result
                        log(
                            f"Oven {oven.get('id')} result captured: {str(st2_result)[:100]}...",
                            req_id=req_id,
                        )

                    # Capture error message if failed
                    if st2_status == "failed":
                        error_msg = extract_error_message(st2_data, st2_result)
                        if error_msg:
                            update_data["error_message"] = error_msg
                            log(f"Oven {oven.get('id')} failed: {error_msg}", req_id=req_id)
                    elif st2_status == "canceled":
                        update_data["error_message"] = "Execution was canceled"

                    requests.put(
                        f"{POUNDCAKE_API_URL}/ovens/{oven.get('id')}",
                        json=update_data,
                        headers=headers,
                        timeout=10,
                    )
                    log(
                        f"Oven {oven.get('id')} marked {new_status} (ST2: {st2_status}) at {current_time}",
                        req_id=req_id,
                    )

    except Exception as e:
        log(f"Error in monitor loop: {str(e)}")


def wait_for_api():
    """Wait for API to be ready before starting main loop."""
    log("Waiting for API to be ready")
    max_attempts = 30
    attempt = 0

    while attempt < max_attempts:
        try:
            resp = requests.get(f"{POUNDCAKE_API_URL}/health", timeout=5)
            if resp.status_code == 200:
                log("API is ready! Starting timer monitor...")
                return True
        except Exception:
            pass

        attempt += 1
        if attempt < max_attempts:
            time.sleep(2)  # Check every 2 seconds

    log(f"API did not become ready after {max_attempts} attempts. Starting anyway...")
    return False


if __name__ == "__main__":
    wait_for_api()
    log(f"Timer Monitor started. Polling interval: {TIMER_INTERVAL}s")

    while True:
        monitor_ovens()
        time.sleep(TIMER_INTERVAL)
