# ____                        _  ____      _
# |  _ \ ___  _   _ _ __   __| |/ ___|__ _| | _____
# | |_) / _ \| | | | '_ \ / _` | |   / _` | |/ / _ \
# |  __/ (_) | |_| | | | | (_| | |__| (_| |   <  __/
# |_|   \___/ \__,_|_| |_|\__,_|\____\__,_|_|\_\___|
#
apiVersion: v2
name: poundcake
description: Auto-remediation platform bridging Prometheus Alertmanager with StackStorm and optional Bakery ticket translation
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the chart's dependencies.
version: 0.2.106

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "2.0.207"

maintainers:
  - name: Jake Briggs
keywords:
  - alertmanager
  - stackstorm
  - auto-remediation
  - prometheus
  - automation
home: https://github.com/rackerlabs/poundcake
sources:
  - https://github.com/rackerlabs/poundcake
